### ISSUE TITLE
Проверка лабораторной работы 2 (задание 2)

### ISSUE THREAD

**Issue by hihamidkz** [hihamidkz/equation#1]
Работу выполнил Казимов Хамидулла, группа ИВ-522
To: @evgeny-p

**Comment by evgeny-p** [comment]
При первой попытке сдачи лабораторной работы был ряд замечаний (https://github.com/hihamidkz/equations/issues/1). Предлагалось переписать историю репозитория и были данны ссылки на необходимую для этого документацию. Вместо этого работа была выполнена с нуля в новом репозитории. Такой способ исправления ошибок будет неприемлем при работе над командным проектом.

В текущем виде работа принимается, но в будущем будет лучше разобраться с переписыванием истории репозитория.

**Comment by hihamidkz** [comment]
*comment*
